// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsF2EVsO3awKpkojJRCa1YaOPQPA0_ves',
    appId: '1:261719020003:web:c28160b5ebb616e43410d6',
    messagingSenderId: '261719020003',
    projectId: 'sunny-base',
    authDomain: 'sunny-base.firebaseapp.com',
    databaseURL: 'https://sunny-base-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sunny-base.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgep9gA83aQKkgJOQwlmoXD8SG5h20uUg',
    appId: '1:261719020003:android:d22a052c9a48cd493410d6',
    messagingSenderId: '261719020003',
    projectId: 'sunny-base',
    databaseURL: 'https://sunny-base-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sunny-base.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0elix17EYVUl3c4a4TRAMKmciOl7pBOg',
    appId: '1:261719020003:ios:0e3e8c65e94784cc3410d6',
    messagingSenderId: '261719020003',
    projectId: 'sunny-base',
    databaseURL: 'https://sunny-base-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sunny-base.appspot.com',
    androidClientId: '261719020003-rjp146b4bgrlppqo97jpr92q7bt4ajjo.apps.googleusercontent.com',
    iosClientId: '261719020003-ioo54afatrdiqu26g7nc5472mv2l8p0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.synnySpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0elix17EYVUl3c4a4TRAMKmciOl7pBOg',
    appId: '1:261719020003:ios:0e3e8c65e94784cc3410d6',
    messagingSenderId: '261719020003',
    projectId: 'sunny-base',
    databaseURL: 'https://sunny-base-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sunny-base.appspot.com',
    androidClientId: '261719020003-rjp146b4bgrlppqo97jpr92q7bt4ajjo.apps.googleusercontent.com',
    iosClientId: '261719020003-ioo54afatrdiqu26g7nc5472mv2l8p0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.synnySpace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsF2EVsO3awKpkojJRCa1YaOPQPA0_ves',
    appId: '1:261719020003:web:23c1c178b12183d03410d6',
    messagingSenderId: '261719020003',
    projectId: 'sunny-base',
    authDomain: 'sunny-base.firebaseapp.com',
    databaseURL: 'https://sunny-base-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sunny-base.appspot.com',
  );

}